### ISSUE TITLE
User Icon not working in all themes in aether

### ISSUE THREAD

**Issue by austinrojers** [JezerM/Aether#3]
**Expected behavior**

User icons should be present in all themes

**Actual behaviour**

User Icon not working in all themes in the aether.
It appears only in:
Arch
El Capitan
Material Green
Material Pink

and not in others.

This happens in both _web-greeter_ and _nody-greeeter_

This issue was also present in NoiSek's original project when I used to use lightdm-webkit2-greeter

**Screenshots**

Arch theme:
![Screenshot from 2022-01-06 13-00-54](https://user-images.githubusercontent.com/87067093/148345722-4eb9bcd4-3173-4284-be53-7d66b467a379.png)

Glass theme:
![Screenshot from 2022-01-06 13-01-51](https://user-images.githubusercontent.com/87067093/148345806-f454ce56-ce73-430e-96ee-db824d9af734.png)

There is nothing in the logs

**Comment by JezerM** [comment]
Some themes just have the "Show avatar" option disabled by default, if you don't like it, enable it.

Here're the settings:

![image](https://user-images.githubusercontent.com/59768785/148425690-29beef14-c39a-4894-9358-657f8949dafb.png)

Then, you could just save the current settings as another theme~

[See this video](https://streamable.com/5zn6sk) (Recorded on iOS)

**Comment by austinrojers** [comment]
Oh sorry my bad, it was just a scroll down.
Thanks
