### ISSUE TITLE
Add the logo for NixOS

### ISSUE THREAD

**Issue by ObsidianChickenz** [JezerM/Aether#5]
**Is your feature request related to a problem? Please describe.**
No, there's no problem.

**Describe the solution you'd like**
I would like the logo for NixOS to be added to the list of OS logos.

**Describe alternatives you've considered**
I could use the Tux logo, but I'd prefer to have a specific OS logo.

**Additional context**
I'm trying to get Nody-Greeter and this theme packaged in NixOS. I created a package request, so I'm hoping that they'll be added.

**Comment by JezerM** [comment]
Done, NixOS logo added in latest commit cc65dd53f99f120b. You can pull and use it~

It's nice that you're trying to get these packages in NixOS :D. If I get some time, I could try to create the packages; though I haven't tried NixOS.

**Comment by ghost** [comment]
Thanks for the quick response, and thanks for carrying on the Webkit greeter!
